language: node_js
node_js:
  - "0.10"
  - "0.11"
matrix:
  allow_failures:
    - node_js: "0.11"
  fast_finish: true
after_script:
  - npm test
  - npm run benchmark
notifications:
  irc: chat.freenode.net#hpool-dev
  email: false
